services:
  web:
    build: .
    command: gunicorn --chdir /usr/src/app/business_card/ business_card.wsgi:application -b 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - static_data:/usr/src/app/static
      - media_data:/usr/src/app/media
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/usr/src/app/static
      - media_data:/usr/src/app/media
    depends_on:
      - web

volumes:
  static_data:
  media_data: